# This file is only used to pre-build room images with custom names expected by the backend
# We never run these services with docker compose

services:
    insider-node:
        image: ghcr.io/gibitop/interview-platform-insider-node:latest
        build:
            context: ./insider
            dockerfile: ../dockerfiles/insider-node.Dockerfile
            args:
                PERSISTENCE_DIRECTORY_PATH: $INSIDER_PERSISTENCE_DIRECTORY_PATH
                WORKING_DIRECTORY: $INSIDER_WORKING_DIRECTORY
                START_ACTIVE_FILE_NAME: $INSIDER_START_ACTIVE_FILE_NAME
