services:
    web:
        build:
            context: ./
            dockerfile: ./web/Dockerfile
        restart: always
        ports: [0.0.0.0:3000:4173]
    backend:
        build: './backend'
        restart: always
        ports: [0.0.0.0:3001:4444]
        depends_on:
            db:
                condition: service_healthy
        environment:
            DATABASE_URL: 'postgres://postgres:password@db:5432/interview-platform'
            DOCKER_SOCKET_PATH: '/var/run/docker.sock'
            HASHING_SECRET_HEX: ''
    db:
        image: postgres
        restart: always
        user: 'postgres'
        environment:
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: 'interview-platform'
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10

volumes:
    pgdata:
